# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from test_cases_agent.proto import ecommerce_domain_pb2 as ecommerce__domain__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ecommerce_domain_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EcommerceDomainServiceStub(object):
    """Service exposed by eCommerce Domain Agent
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDomainContext = channel.unary_unary(
                '/ecommerce.domain.v1.EcommerceDomainService/GetDomainContext',
                request_serializer=ecommerce__domain__pb2.DomainContextRequest.SerializeToString,
                response_deserializer=ecommerce__domain__pb2.DomainContextResponse.FromString,
                _registered_method=True)
        self.QueryKnowledge = channel.unary_unary(
                '/ecommerce.domain.v1.EcommerceDomainService/QueryKnowledge',
                request_serializer=ecommerce__domain__pb2.KnowledgeRequest.SerializeToString,
                response_deserializer=ecommerce__domain__pb2.KnowledgeResponse.FromString,
                _registered_method=True)
        self.GetEntity = channel.unary_unary(
                '/ecommerce.domain.v1.EcommerceDomainService/GetEntity',
                request_serializer=ecommerce__domain__pb2.EntityRequest.SerializeToString,
                response_deserializer=ecommerce__domain__pb2.EntityResponse.FromString,
                _registered_method=True)
        self.GetWorkflow = channel.unary_unary(
                '/ecommerce.domain.v1.EcommerceDomainService/GetWorkflow',
                request_serializer=ecommerce__domain__pb2.WorkflowRequest.SerializeToString,
                response_deserializer=ecommerce__domain__pb2.WorkflowResponse.FromString,
                _registered_method=True)
        self.ListEntities = channel.unary_unary(
                '/ecommerce.domain.v1.EcommerceDomainService/ListEntities',
                request_serializer=ecommerce__domain__pb2.ListEntitiesRequest.SerializeToString,
                response_deserializer=ecommerce__domain__pb2.ListEntitiesResponse.FromString,
                _registered_method=True)
        self.ListWorkflows = channel.unary_unary(
                '/ecommerce.domain.v1.EcommerceDomainService/ListWorkflows',
                request_serializer=ecommerce__domain__pb2.ListWorkflowsRequest.SerializeToString,
                response_deserializer=ecommerce__domain__pb2.ListWorkflowsResponse.FromString,
                _registered_method=True)
        self.GetEdgeCases = channel.unary_unary(
                '/ecommerce.domain.v1.EcommerceDomainService/GetEdgeCases',
                request_serializer=ecommerce__domain__pb2.EdgeCasesRequest.SerializeToString,
                response_deserializer=ecommerce__domain__pb2.EdgeCasesResponse.FromString,
                _registered_method=True)
        self.GenerateTestData = channel.unary_unary(
                '/ecommerce.domain.v1.EcommerceDomainService/GenerateTestData',
                request_serializer=ecommerce__domain__pb2.GenerateTestDataRequest.SerializeToString,
                response_deserializer=ecommerce__domain__pb2.GenerateTestDataResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/ecommerce.domain.v1.EcommerceDomainService/HealthCheck',
                request_serializer=ecommerce__domain__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=ecommerce__domain__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class EcommerceDomainServiceServicer(object):
    """Service exposed by eCommerce Domain Agent
    """

    def GetDomainContext(self, request, context):
        """Get domain context for test generation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryKnowledge(self, request, context):
        """Query domain knowledge
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntity(self, request, context):
        """Get entity details
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkflow(self, request, context):
        """Get workflow details
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEntities(self, request, context):
        """List all entities
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkflows(self, request, context):
        """List all workflows
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEdgeCases(self, request, context):
        """Get edge cases for an entity/workflow
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateTestData(self, request, context):
        """Generate test data (proxies to Test Data Agent with domain context)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EcommerceDomainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDomainContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDomainContext,
                    request_deserializer=ecommerce__domain__pb2.DomainContextRequest.FromString,
                    response_serializer=ecommerce__domain__pb2.DomainContextResponse.SerializeToString,
            ),
            'QueryKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryKnowledge,
                    request_deserializer=ecommerce__domain__pb2.KnowledgeRequest.FromString,
                    response_serializer=ecommerce__domain__pb2.KnowledgeResponse.SerializeToString,
            ),
            'GetEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntity,
                    request_deserializer=ecommerce__domain__pb2.EntityRequest.FromString,
                    response_serializer=ecommerce__domain__pb2.EntityResponse.SerializeToString,
            ),
            'GetWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkflow,
                    request_deserializer=ecommerce__domain__pb2.WorkflowRequest.FromString,
                    response_serializer=ecommerce__domain__pb2.WorkflowResponse.SerializeToString,
            ),
            'ListEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEntities,
                    request_deserializer=ecommerce__domain__pb2.ListEntitiesRequest.FromString,
                    response_serializer=ecommerce__domain__pb2.ListEntitiesResponse.SerializeToString,
            ),
            'ListWorkflows': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkflows,
                    request_deserializer=ecommerce__domain__pb2.ListWorkflowsRequest.FromString,
                    response_serializer=ecommerce__domain__pb2.ListWorkflowsResponse.SerializeToString,
            ),
            'GetEdgeCases': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEdgeCases,
                    request_deserializer=ecommerce__domain__pb2.EdgeCasesRequest.FromString,
                    response_serializer=ecommerce__domain__pb2.EdgeCasesResponse.SerializeToString,
            ),
            'GenerateTestData': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateTestData,
                    request_deserializer=ecommerce__domain__pb2.GenerateTestDataRequest.FromString,
                    response_serializer=ecommerce__domain__pb2.GenerateTestDataResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=ecommerce__domain__pb2.HealthCheckRequest.FromString,
                    response_serializer=ecommerce__domain__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ecommerce.domain.v1.EcommerceDomainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ecommerce.domain.v1.EcommerceDomainService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EcommerceDomainService(object):
    """Service exposed by eCommerce Domain Agent
    """

    @staticmethod
    def GetDomainContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.domain.v1.EcommerceDomainService/GetDomainContext',
            ecommerce__domain__pb2.DomainContextRequest.SerializeToString,
            ecommerce__domain__pb2.DomainContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.domain.v1.EcommerceDomainService/QueryKnowledge',
            ecommerce__domain__pb2.KnowledgeRequest.SerializeToString,
            ecommerce__domain__pb2.KnowledgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.domain.v1.EcommerceDomainService/GetEntity',
            ecommerce__domain__pb2.EntityRequest.SerializeToString,
            ecommerce__domain__pb2.EntityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.domain.v1.EcommerceDomainService/GetWorkflow',
            ecommerce__domain__pb2.WorkflowRequest.SerializeToString,
            ecommerce__domain__pb2.WorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.domain.v1.EcommerceDomainService/ListEntities',
            ecommerce__domain__pb2.ListEntitiesRequest.SerializeToString,
            ecommerce__domain__pb2.ListEntitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkflows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.domain.v1.EcommerceDomainService/ListWorkflows',
            ecommerce__domain__pb2.ListWorkflowsRequest.SerializeToString,
            ecommerce__domain__pb2.ListWorkflowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEdgeCases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.domain.v1.EcommerceDomainService/GetEdgeCases',
            ecommerce__domain__pb2.EdgeCasesRequest.SerializeToString,
            ecommerce__domain__pb2.EdgeCasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateTestData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.domain.v1.EcommerceDomainService/GenerateTestData',
            ecommerce__domain__pb2.GenerateTestDataRequest.SerializeToString,
            ecommerce__domain__pb2.GenerateTestDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.domain.v1.EcommerceDomainService/HealthCheck',
            ecommerce__domain__pb2.HealthCheckRequest.SerializeToString,
            ecommerce__domain__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
