# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from test_cases_agent.proto import test_cases_pb2 as test__cases__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in test_cases_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TestCasesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateTestCases = channel.unary_unary(
                '/testcases.v1.TestCasesService/GenerateTestCases',
                request_serializer=test__cases__pb2.GenerateTestCasesRequest.SerializeToString,
                response_deserializer=test__cases__pb2.GenerateTestCasesResponse.FromString,
                _registered_method=True)
        self.GetTestCase = channel.unary_unary(
                '/testcases.v1.TestCasesService/GetTestCase',
                request_serializer=test__cases__pb2.GetTestCaseRequest.SerializeToString,
                response_deserializer=test__cases__pb2.GetTestCaseResponse.FromString,
                _registered_method=True)
        self.ListTestCases = channel.unary_unary(
                '/testcases.v1.TestCasesService/ListTestCases',
                request_serializer=test__cases__pb2.ListTestCasesRequest.SerializeToString,
                response_deserializer=test__cases__pb2.ListTestCasesResponse.FromString,
                _registered_method=True)
        self.StoreTestCases = channel.unary_unary(
                '/testcases.v1.TestCasesService/StoreTestCases',
                request_serializer=test__cases__pb2.StoreTestCasesRequest.SerializeToString,
                response_deserializer=test__cases__pb2.StoreTestCasesResponse.FromString,
                _registered_method=True)
        self.AnalyzeCoverage = channel.unary_unary(
                '/testcases.v1.TestCasesService/AnalyzeCoverage',
                request_serializer=test__cases__pb2.AnalyzeCoverageRequest.SerializeToString,
                response_deserializer=test__cases__pb2.AnalyzeCoverageResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/testcases.v1.TestCasesService/HealthCheck',
                request_serializer=test__cases__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=test__cases__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class TestCasesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateTestCases(self, request, context):
        """Generate test cases from requirements
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTestCase(self, request, context):
        """Get a specific test case by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTestCases(self, request, context):
        """List historical test cases
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreTestCases(self, request, context):
        """Store test cases (for learning)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeCoverage(self, request, context):
        """Get coverage analysis for requirements
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestCasesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateTestCases': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateTestCases,
                    request_deserializer=test__cases__pb2.GenerateTestCasesRequest.FromString,
                    response_serializer=test__cases__pb2.GenerateTestCasesResponse.SerializeToString,
            ),
            'GetTestCase': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTestCase,
                    request_deserializer=test__cases__pb2.GetTestCaseRequest.FromString,
                    response_serializer=test__cases__pb2.GetTestCaseResponse.SerializeToString,
            ),
            'ListTestCases': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTestCases,
                    request_deserializer=test__cases__pb2.ListTestCasesRequest.FromString,
                    response_serializer=test__cases__pb2.ListTestCasesResponse.SerializeToString,
            ),
            'StoreTestCases': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreTestCases,
                    request_deserializer=test__cases__pb2.StoreTestCasesRequest.FromString,
                    response_serializer=test__cases__pb2.StoreTestCasesResponse.SerializeToString,
            ),
            'AnalyzeCoverage': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeCoverage,
                    request_deserializer=test__cases__pb2.AnalyzeCoverageRequest.FromString,
                    response_serializer=test__cases__pb2.AnalyzeCoverageResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=test__cases__pb2.HealthCheckRequest.FromString,
                    response_serializer=test__cases__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'testcases.v1.TestCasesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('testcases.v1.TestCasesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TestCasesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateTestCases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testcases.v1.TestCasesService/GenerateTestCases',
            test__cases__pb2.GenerateTestCasesRequest.SerializeToString,
            test__cases__pb2.GenerateTestCasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTestCase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testcases.v1.TestCasesService/GetTestCase',
            test__cases__pb2.GetTestCaseRequest.SerializeToString,
            test__cases__pb2.GetTestCaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTestCases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testcases.v1.TestCasesService/ListTestCases',
            test__cases__pb2.ListTestCasesRequest.SerializeToString,
            test__cases__pb2.ListTestCasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreTestCases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testcases.v1.TestCasesService/StoreTestCases',
            test__cases__pb2.StoreTestCasesRequest.SerializeToString,
            test__cases__pb2.StoreTestCasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeCoverage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testcases.v1.TestCasesService/AnalyzeCoverage',
            test__cases__pb2.AnalyzeCoverageRequest.SerializeToString,
            test__cases__pb2.AnalyzeCoverageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testcases.v1.TestCasesService/HealthCheck',
            test__cases__pb2.HealthCheckRequest.SerializeToString,
            test__cases__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
