# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import test_data_pb2 as test__data__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in test_data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TestDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateData = channel.unary_unary(
                '/testdata.v1.TestDataService/GenerateData',
                request_serializer=test__data__pb2.GenerateRequest.SerializeToString,
                response_deserializer=test__data__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.GenerateDataStream = channel.unary_stream(
                '/testdata.v1.TestDataService/GenerateDataStream',
                request_serializer=test__data__pb2.GenerateRequest.SerializeToString,
                response_deserializer=test__data__pb2.DataChunk.FromString,
                _registered_method=True)
        self.GetSchemas = channel.unary_unary(
                '/testdata.v1.TestDataService/GetSchemas',
                request_serializer=test__data__pb2.GetSchemasRequest.SerializeToString,
                response_deserializer=test__data__pb2.GetSchemasResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/testdata.v1.TestDataService/HealthCheck',
                request_serializer=test__data__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=test__data__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class TestDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateData(self, request, context):
        """Synchronous generation for small requests (<1000 records)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateDataStream(self, request, context):
        """Streaming for large requests
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchemas(self, request, context):
        """List available schemas
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateData': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateData,
                    request_deserializer=test__data__pb2.GenerateRequest.FromString,
                    response_serializer=test__data__pb2.GenerateResponse.SerializeToString,
            ),
            'GenerateDataStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateDataStream,
                    request_deserializer=test__data__pb2.GenerateRequest.FromString,
                    response_serializer=test__data__pb2.DataChunk.SerializeToString,
            ),
            'GetSchemas': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchemas,
                    request_deserializer=test__data__pb2.GetSchemasRequest.FromString,
                    response_serializer=test__data__pb2.GetSchemasResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=test__data__pb2.HealthCheckRequest.FromString,
                    response_serializer=test__data__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'testdata.v1.TestDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('testdata.v1.TestDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TestDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testdata.v1.TestDataService/GenerateData',
            test__data__pb2.GenerateRequest.SerializeToString,
            test__data__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateDataStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/testdata.v1.TestDataService/GenerateDataStream',
            test__data__pb2.GenerateRequest.SerializeToString,
            test__data__pb2.DataChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSchemas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testdata.v1.TestDataService/GetSchemas',
            test__data__pb2.GetSchemasRequest.SerializeToString,
            test__data__pb2.GetSchemasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testdata.v1.TestDataService/HealthCheck',
            test__data__pb2.HealthCheckRequest.SerializeToString,
            test__data__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
