# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import requirement_analysis_pb2 as requirement__analysis__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in requirement_analysis_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RequirementAnalysisServiceStub(object):
    """=============================================================================
    Requirement Analysis Service
    Analyzes requirements from multiple input formats, assesses quality,
    identifies gaps, and prepares structured output for test case generation.
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeRequirement = channel.unary_unary(
                '/requirementanalysis.v1.RequirementAnalysisService/AnalyzeRequirement',
                request_serializer=requirement__analysis__pb2.AnalyzeRequest.SerializeToString,
                response_deserializer=requirement__analysis__pb2.AnalyzeResponse.FromString,
                _registered_method=True)
        self.ReanalyzeRequirement = channel.unary_unary(
                '/requirementanalysis.v1.RequirementAnalysisService/ReanalyzeRequirement',
                request_serializer=requirement__analysis__pb2.ReanalyzeRequest.SerializeToString,
                response_deserializer=requirement__analysis__pb2.AnalyzeResponse.FromString,
                _registered_method=True)
        self.ExportAnalysis = channel.unary_unary(
                '/requirementanalysis.v1.RequirementAnalysisService/ExportAnalysis',
                request_serializer=requirement__analysis__pb2.ExportRequest.SerializeToString,
                response_deserializer=requirement__analysis__pb2.ExportResponse.FromString,
                _registered_method=True)
        self.ForwardToTestCases = channel.unary_unary(
                '/requirementanalysis.v1.RequirementAnalysisService/ForwardToTestCases',
                request_serializer=requirement__analysis__pb2.ForwardRequest.SerializeToString,
                response_deserializer=requirement__analysis__pb2.ForwardResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/requirementanalysis.v1.RequirementAnalysisService/HealthCheck',
                request_serializer=requirement__analysis__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=requirement__analysis__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.ListHistory = channel.unary_unary(
                '/requirementanalysis.v1.RequirementAnalysisService/ListHistory',
                request_serializer=requirement__analysis__pb2.ListHistoryRequest.SerializeToString,
                response_deserializer=requirement__analysis__pb2.ListHistoryResponse.FromString,
                _registered_method=True)
        self.GetHistorySession = channel.unary_unary(
                '/requirementanalysis.v1.RequirementAnalysisService/GetHistorySession',
                request_serializer=requirement__analysis__pb2.GetHistorySessionRequest.SerializeToString,
                response_deserializer=requirement__analysis__pb2.GetHistorySessionResponse.FromString,
                _registered_method=True)
        self.DeleteHistorySession = channel.unary_unary(
                '/requirementanalysis.v1.RequirementAnalysisService/DeleteHistorySession',
                request_serializer=requirement__analysis__pb2.DeleteHistorySessionRequest.SerializeToString,
                response_deserializer=requirement__analysis__pb2.DeleteHistorySessionResponse.FromString,
                _registered_method=True)
        self.SearchHistory = channel.unary_unary(
                '/requirementanalysis.v1.RequirementAnalysisService/SearchHistory',
                request_serializer=requirement__analysis__pb2.SearchHistoryRequest.SerializeToString,
                response_deserializer=requirement__analysis__pb2.SearchHistoryResponse.FromString,
                _registered_method=True)


class RequirementAnalysisServiceServicer(object):
    """=============================================================================
    Requirement Analysis Service
    Analyzes requirements from multiple input formats, assesses quality,
    identifies gaps, and prepares structured output for test case generation.
    =============================================================================

    """

    def AnalyzeRequirement(self, request, context):
        """Analyze a requirement from any input type (Jira, free-form, transcript)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReanalyzeRequirement(self, request, context):
        """Re-analyze with updates (questions answered, edits made)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportAnalysis(self, request, context):
        """Export analysis report in text or JSON format
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForwardToTestCases(self, request, context):
        """Forward analyzed requirement to Test Cases Agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListHistory(self, request, context):
        """==========================================================================
        History Management
        ==========================================================================

        List analysis history with pagination and filters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistorySession(self, request, context):
        """Get full details of a history session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteHistorySession(self, request, context):
        """Delete a history session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchHistory(self, request, context):
        """Search history by keyword
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RequirementAnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeRequirement': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeRequirement,
                    request_deserializer=requirement__analysis__pb2.AnalyzeRequest.FromString,
                    response_serializer=requirement__analysis__pb2.AnalyzeResponse.SerializeToString,
            ),
            'ReanalyzeRequirement': grpc.unary_unary_rpc_method_handler(
                    servicer.ReanalyzeRequirement,
                    request_deserializer=requirement__analysis__pb2.ReanalyzeRequest.FromString,
                    response_serializer=requirement__analysis__pb2.AnalyzeResponse.SerializeToString,
            ),
            'ExportAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportAnalysis,
                    request_deserializer=requirement__analysis__pb2.ExportRequest.FromString,
                    response_serializer=requirement__analysis__pb2.ExportResponse.SerializeToString,
            ),
            'ForwardToTestCases': grpc.unary_unary_rpc_method_handler(
                    servicer.ForwardToTestCases,
                    request_deserializer=requirement__analysis__pb2.ForwardRequest.FromString,
                    response_serializer=requirement__analysis__pb2.ForwardResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=requirement__analysis__pb2.HealthCheckRequest.FromString,
                    response_serializer=requirement__analysis__pb2.HealthCheckResponse.SerializeToString,
            ),
            'ListHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.ListHistory,
                    request_deserializer=requirement__analysis__pb2.ListHistoryRequest.FromString,
                    response_serializer=requirement__analysis__pb2.ListHistoryResponse.SerializeToString,
            ),
            'GetHistorySession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistorySession,
                    request_deserializer=requirement__analysis__pb2.GetHistorySessionRequest.FromString,
                    response_serializer=requirement__analysis__pb2.GetHistorySessionResponse.SerializeToString,
            ),
            'DeleteHistorySession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteHistorySession,
                    request_deserializer=requirement__analysis__pb2.DeleteHistorySessionRequest.FromString,
                    response_serializer=requirement__analysis__pb2.DeleteHistorySessionResponse.SerializeToString,
            ),
            'SearchHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchHistory,
                    request_deserializer=requirement__analysis__pb2.SearchHistoryRequest.FromString,
                    response_serializer=requirement__analysis__pb2.SearchHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'requirementanalysis.v1.RequirementAnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('requirementanalysis.v1.RequirementAnalysisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RequirementAnalysisService(object):
    """=============================================================================
    Requirement Analysis Service
    Analyzes requirements from multiple input formats, assesses quality,
    identifies gaps, and prepares structured output for test case generation.
    =============================================================================

    """

    @staticmethod
    def AnalyzeRequirement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/requirementanalysis.v1.RequirementAnalysisService/AnalyzeRequirement',
            requirement__analysis__pb2.AnalyzeRequest.SerializeToString,
            requirement__analysis__pb2.AnalyzeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReanalyzeRequirement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/requirementanalysis.v1.RequirementAnalysisService/ReanalyzeRequirement',
            requirement__analysis__pb2.ReanalyzeRequest.SerializeToString,
            requirement__analysis__pb2.AnalyzeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/requirementanalysis.v1.RequirementAnalysisService/ExportAnalysis',
            requirement__analysis__pb2.ExportRequest.SerializeToString,
            requirement__analysis__pb2.ExportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForwardToTestCases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/requirementanalysis.v1.RequirementAnalysisService/ForwardToTestCases',
            requirement__analysis__pb2.ForwardRequest.SerializeToString,
            requirement__analysis__pb2.ForwardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/requirementanalysis.v1.RequirementAnalysisService/HealthCheck',
            requirement__analysis__pb2.HealthCheckRequest.SerializeToString,
            requirement__analysis__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/requirementanalysis.v1.RequirementAnalysisService/ListHistory',
            requirement__analysis__pb2.ListHistoryRequest.SerializeToString,
            requirement__analysis__pb2.ListHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistorySession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/requirementanalysis.v1.RequirementAnalysisService/GetHistorySession',
            requirement__analysis__pb2.GetHistorySessionRequest.SerializeToString,
            requirement__analysis__pb2.GetHistorySessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteHistorySession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/requirementanalysis.v1.RequirementAnalysisService/DeleteHistorySession',
            requirement__analysis__pb2.DeleteHistorySessionRequest.SerializeToString,
            requirement__analysis__pb2.DeleteHistorySessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/requirementanalysis.v1.RequirementAnalysisService/SearchHistory',
            requirement__analysis__pb2.SearchHistoryRequest.SerializeToString,
            requirement__analysis__pb2.SearchHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
