"""Pydantic models for requirement analysis."""

from .analysis import (
    InputType,
    GapCategory,
    Severity,
    Grade,
    QuestionCategory,
    ACSource,
    DimensionScore,
    QualityScore,
    RequirementStructure,
    ExtractedRequirement,
    Gap,
    ClarifyingQuestion,
    GeneratedAC,
    EntityMapping,
    ApplicableRule,
    DomainWarning,
    DomainValidation,
    AnalysisMetadata,
    OriginalInput,
    AnalysisResult,
)
from .inputs import (
    JiraStoryInput,
    FreeFormInput,
    TranscriptInput,
    AnalysisConfig,
    AnsweredQuestion,
    ACDecision,
    ReanalyzeInput,
    ForwardTestCasesConfig,
    ForwardInput,
    ExportConfig,
    StructuredRequirement,
)

__all__ = [
    # Enums
    "InputType",
    "GapCategory",
    "Severity",
    "Grade",
    "QuestionCategory",
    "ACSource",
    # Analysis Models
    "DimensionScore",
    "QualityScore",
    "RequirementStructure",
    "ExtractedRequirement",
    "Gap",
    "ClarifyingQuestion",
    "GeneratedAC",
    "EntityMapping",
    "ApplicableRule",
    "DomainWarning",
    "DomainValidation",
    "AnalysisMetadata",
    "OriginalInput",
    "AnalysisResult",
    # Input Models
    "JiraStoryInput",
    "FreeFormInput",
    "TranscriptInput",
    "AnalysisConfig",
    "AnsweredQuestion",
    "ACDecision",
    "ReanalyzeInput",
    "ForwardTestCasesConfig",
    "ForwardInput",
    "ExportConfig",
    "StructuredRequirement",
]
